module.exports = {
  "Needs Triage": undefined,
  Backlog: "WB: 1 - Backlog",
  "Mockups - Requested": "WB: 2.1 - Mockups Requested",
  "Mockups - In Progress": "WB: 2.2 - Mockups In Progress",
  "Mockups - In Review": "WB: 2.3 - Mockups Under Review",
  "Mockups - Approved": "WB: 2.4 - Mockups Approved",
  "Bug - In Diagnostics": "WB: 5.1 - Bug Diagnostics",
  "Bug - Can't Replicate": "WB: 1.1 - Bug Cannot Replicate",
  "Staged for Sprint (Dev Pool)": "WB: 3 - Current Sprint",
  "In Development": "WB: 5 - In Progress",
  "PR Review": "WB: 6 - Review",
  "Failed PR Review": "WB: 4 - Remediation",
  Merged: "WB: 7 - Merged",
  "In Release QA": "WB: 9 - Release QA",
  "Passed Release QA": "WB: 9.5 - Release QA - Passed",
  "Failed Release QA": "WB: 8 - Release QA - Failed",
  "Will not implement": "WB: 9.9 - Will Not Implement",
  Deployed: "WB: 9.6 - Deployed"
};
